# Generated by Django 2.0.1 on 2018-04-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arpuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Check if is staff ', verbose_name='Staff Status'),
        ),
    ]
