# Generated by Django 2.0.1 on 2018-04-14 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARP', '0002_arpuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim_mac', models.CharField(max_length=100, verbose_name='MAC Address(Victim)')),
                ('victim_ip', models.CharField(max_length=100, verbose_name='IP Address(Victim)')),
                ('pretend_mac', models.CharField(max_length=100, verbose_name='MAC Address(Pretend)')),
                ('pretend_ip', models.CharField(max_length=100, verbose_name='IP Address(Pretend)')),
                ('timestamp', models.DateTimeField(verbose_name='Date/Time of Infection')),
                ('victim_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARP.ARPUser', verbose_name='Victim')),
            ],
        ),
    ]
