# Generated by Django 2.0.1 on 2018-04-14 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARP', '0005_auto_20180414_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='arpuser',
            name='employee_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='infection',
            name='victim_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infections', to='ARP.ARPUser', verbose_name='Victim'),
        ),
    ]
