# Generated by Django 2.0.1 on 2018-04-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARP', '0006_auto_20180414_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('INF', 'Infection'), ('FIX', 'Fixed')], max_length=3)),
                ('timestamp', models.DateTimeField(verbose_name='Date/Time')),
                ('victim_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ARP.ARPUser')),
            ],
        ),
        migrations.AlterField(
            model_name='infection',
            name='victim_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infections', to='ARP.ARPUser', verbose_name='Victim'),
        ),
    ]
